### PR TITLE
chore: add cncf logo and text to the footer

### PR DESCRIPTION
**Pull request by shahramk64**
As one of the tasks required for donating Ratify to a open-source foundation, we must include the sentence “We are a Cloud Native Computing Foundation project.” and the CNCF logo near the bottom of their project homepage. Sandbox-level projects should include the sentence “We are a Cloud Native Computing Foundation sandbox project.” and the CNCF logo.
Fixes Issue #116 

This is how the footer going to look:
image

### CODE REVIEW

**Review by susanshi — COMMENTED** [review]
thanks for the PR @shahramk64. The footer looks great.  Is it possible to add comments around where we source these images and theme files? we would know where to find image/theme if updates are required in the future. If adding comment is not possible, maybe we can just capture notes in the PR.

**Comment by shahramk64** [comment]
The theme and logo images from the ORAS repo were used in this PR. The commit sha that included this change in the ORAS repo is "4ab2c1b93dfe3496553655f8b15b9c19cfed0f5c". 
The actual logo can be obtained from https://www.cncf.io/brand-guidelines/#logo

**Review by susanshi — APPROVED** [review]
Looks good to me. thanks!

**Review by junczhu — APPROVED** [review]
LGTM

**Review by binbin-li — APPROVED** [review]
lgtm, thanks for adding it!

**Pull request merged**
